In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
#data_types
x=np.array([1,2,3,4],dtype=float)
print("np.array([1,2,3,4],dtype=float) : ",x)

np.array([1,2,3,4],dtype=float) :  [1. 2. 3. 4.]


In [5]:
#shape of the array
s=np.array([3,2,14,5])
print("s.shape :",s.shape)

s.shape : (4,)


In [7]:
#sum of two arrays
arr1=np.array([1,2,5,3,7])
print("arr1 :",arr1)
print("arr1.shape :",arr1.shape)
print("arr1.size :",arr1.size)
arr2=np.array([2,1,4,6,8])
print("arr2 :",arr2)

print("arr1+arr2 : ",arr1+arr2)

arr1 : [1 2 5 3 7]
arr1.shape : (5,)
arr1.size : 5
arr2 : [2 1 4 6 8]
arr1+arr2 :  [ 3  3  9  9 15]


In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("Slicing")
print(arr[1:4])
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array")
print(arr)
print("2nd Row 3rd column")
print(arr[1, 2])

[1 2 3 4 5]
Slicing
[2 3 4]
2D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd Row 3rd column
6
